platform :ios, '14.1'

use_frameworks!

target 'ReadDiceKey_Example' do
  pod 'OpenCVXF', :git => 'https://github.com/dicekeys/opencv-xf.git'
  pod 'ReadDiceKey', :path => '../'

  target 'ReadDiceKey_Tests' do
    inherit! :complete

    
  end
end
