platform :ios, '14.1'

use_frameworks!

target 'ReadDiceKey_Example' do
  pod 'OpenCVXF', :path => '../../opencv-xf'
  pod 'ReadDiceKey', :path => '../'

  target 'ReadDiceKey_Tests' do
    inherit! :search_paths

    
  end
end
